apiVersion: v1
kind: Pod
metadata:
  name: wordpress-archive-repo
  labels:
    name: archive
spec:
  containers:
    - name: wordpress-archive-repo
      image: nginx
      volumeMounts:
        - name: archive-persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: archive-persistent-storage
      persistentVolumeClaim:
        claimName: archive-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archive-pv-claim
  labels:
    app: archive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
